"""Generate version_info.txt (PyInstaller Windows version resource) from _version.py.

Keeps vidgrab/_version.py the single source of truth: run this before a
Windows build so VidGrab.exe reports the same version as the app itself.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from vidgrab._version import __version__


def _quad(version: str) -> tuple[int, int, int, int]:
    raw = version.replace("-", "+", 1).split("+", 1)[0]
    parts = [int(p) for p in raw.split(".") if p.isdigit()]
    return tuple((parts + [0, 0, 0, 0])[:4])  # type: ignore[return-value]


def main() -> None:
    major, minor, patch, build = _quad(__version__)
    fv = ", ".join(str(x) for x in (major, minor, patch, build))
    template = f"""# UTF-8
#
# Auto-generated by scripts/write_version_info.py — do not edit.
# Version source: vidgrab/_version.py ({__version__})

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({fv}),
    prodvers=({fv}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'VidGrab Project'),
         StringStruct(u'FileDescription', u'VidGrab - download, flip & trim media'),
         StringStruct(u'FileVersion', u'{__version__}'),
         StringStruct(u'InternalName', u'VidGrab'),
         StringStruct(u'LegalCopyright', u'Copyright (c) 2026'),
         StringStruct(u'OriginalFilename', u'VidGrab.exe'),
         StringStruct(u'ProductName', u'VidGrab'),
         StringStruct(u'ProductVersion', u'{__version__}')]
      )
    ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    out = ROOT / "version_info.txt"
    out.write_text(template, encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()